groups:
  - name: hospital_triage
    rules:
      - alert: HighErrorRate
        expr: increase(total_de_erros_na_api_total[5m]) > 5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Alto número de erros na API detectado"
          description: "A API encontrou mais de 5 erros nos últimos 5 minutos."
      - alert: HighPredictionDuration
        expr: histogram_quantile(0.95, sum by (le) (rate(duracao_da_predicao_segundos_bucket[5m]))) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alta duração da predição detectada"
          description: "O percentil 95 da duração das predições permaneceu acima de 1 segundo."
      - alert: LowAverageConfidence
        expr: sum(rate(confianca_da_predicao_sum[5m])) / sum(rate(confianca_da_predicao_count[5m])) < 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Baixa confiança média das predições detectada"
          description: "A confiança média das predições permaneceu abaixo de 0.5."
